name : Help Center CI
on:
  push:
    branches : 
      - "main"
    
jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v1
      - run : npm install
      - run : npm run build
      - run : sudo rm -r /var/www/help/build
      - run : sudo mv /home/mbe/actions-runner-one/_work/help-center/help-center/build /var/www/help/
      - run : sudo cp /var/www/.htaccess /var/www/help/build


      